### ISSUE TITLE
“Transgender” is not a gender

### ISSUE THREAD

**Issue by rory** [openknowledgebe/equalstreetnames#13]
I've raised this on the IRC channel, but a github issue to track it is helpful. So here we go. 🙂

The current code & website splits humans into 3 categories: “male”, “female” ... and “transgender”. 🤦 Transgender is not a gender.

My suggestion is to have 2 axes of categoriesation: “Male”/“Female”/”Other”, and “Cis”/“Trans”. And all “Other” would automatically be in “Trans” category. So someone could be trans woman, cis male. etc. You could also just have “Male”/“Not Male”, and “Cis”/“Not Cis”.

This means you are misgendering the only trans person on your list, by not referring to him as male.

**Comment by jbelien** [comment]
Hello @rory,
Thanks for your feedback !

We don't state that there is only 3 genders (man/woman/transgender), we state that there are xx streets based on man, xx streets based on woman, and xx streets based on transgender (man or woman)!
The whole point of this project is to highlight the imbalance between the streetnames based on men, women, transgender men, and transgender women !

I get your point but having 2 axis make the "rendering" (in this case, the color) too complicated to render and understand !

Would the following be more "acceptable" ?
- Man (xx %)
- Woman (xx %)
- Transgender man (xx %)
- Transgender woman (0 %)

**Comment by rory** [comment]
“(wo)man” includes “trans (wo)man”, so you'd have to count people twice.

I know 2 axes might be more fractionally complicated, but in the end, as you point out, the end result is 4 categories. I know you didn't _say_ there were only 3 genders (& one of which is trans), but your software splits thing that way. 😉 Software is hard. 🙂 I get that.

If you want to simplify every further, 2 categories/colours of “cis male” and “not cis male” is a possibility, and in line with highlighting the imbalance of names. 🙂

I am attempting to improve the raw wikidata in this way BTW.

**Comment by Manonbd** [comment]
Hi Rory, 
Manon here, who's be working on this project. I'm really sorry for making the mistake as I know that transgender is not a gender. We wanted to emphasize the fact that there's also a lack of representativity of transgender men & women in Brussels so that's why we didn't put it in the main category. 

So you would do one category of "Cis Male" and one of "Not Cis Male" is that correct?

**Comment by rory** [comment]
> So you would do one category of "Cis Male" and one of "Not Cis Male" is that correct?

If it was me, I'd have 2 axes:
> My suggestion is to have 2 axes of categoriesation: “Male”/“Female”/”Other”, and “Cis”/“Trans”. And all “Other” would automatically be in “Trans” category. So someone could be trans woman, cis male. etc

“cis male” vs “not cis male” is a simplication you could use if you only wanted 1 axis.

**Comment by jbelien** [comment]
> “cis male” vs “not cis male” is a simplication you could use if you only wanted 1 axis.

But then women, transgender women, and transgender men are all in one single "category" : "not cis male".

**Comment by jbelien** [comment]
@rory I like the 2 axis but how would you render it on the map ?

**Comment by rory** [comment]
> But then women, transgender women, and transgender men are all in one single "category" : "not cis male".

transgender women _are_ women. Do you mean cis women? Remember “cis men”/“not cis men” isn't my number one suggestion. Yes it lumps people in, but let's be honest. the imbalance in names towards cis men is what you want to highlight, right?

> I like the 2 axis but how would you render it on the map ?

My suggested categorization results in 5 options: “cis men”, “cis women”, ”nonbinary people” (gender=other (which implies trans)), “trans men”, “trans women”. So just choose 5 different colours. You could have 2 views: (i) “men” (cis men + trans men), “women & nb” (cis women, trans women, nonbinary people) (or call that “not men”), requiring only 2 colours, and (ii) “cis” vs “trans”, again requing 2 colours.

Obviously, in reality, it's mostly “cis men”, with some “cis women” and one “trans man”, making most of this theoretical. (Are there _any_ streets named after a nonbinary person? 🤔)

**Comment by jbelien** [comment]
> transgender women _are_ women. Do you mean cis women?

Sorry, I indeed meant cis women (instead of women).

**Comment by rory** [comment]
> I am attempting to improve the raw wikidata in this way BTW.

I have attempted to make some wikidata changes to turn “male” → “cis[gender] male” ([#](https://www.wikidata.org/w/index.php?title=Q12967&diff=prev&oldid=1131253668) [#](https://www.wikidata.org/w/index.php?title=Q12971&diff=prev&oldid=1131253758) [#](https://www.wikidata.org/w/index.php?title=Q12973&diff=prev&oldid=1131253954) [#](https://www.wikidata.org/w/index.php?title=Q12973&diff=prev&oldid=1131300693) [#](https://www.wikidata.org/w/index.php?title=Q12971&diff=prev&oldid=1131300915) [#](https://www.wikidata.org/w/index.php?title=Q12967&diff=prev&oldid=1131301353) 
[#](https://www.wikidata.org/w/index.php?title=Q12967&diff=prev&oldid=1137006762) [#](https://www.wikidata.org/w/index.php?title=Q12973&diff=prev&oldid=1137006805) [#](https://www.wikidata.org/w/index.php?title=Q12971&diff=prev&oldid=1137006833) ). But they were all reverted. It looks like it's not really possible, with Wikidata, to actually support this use case. ([#](https://www.wikidata.org/w/index.php?title=User_talk:Aranya&oldid=1133326863#recent_reverts_w.r.t._cisgender) [#](https://www.wikidata.org/w/index.php?title=User_talk:Ebelular&oldid=1137127834)). I'm not going to persue Wikidata editing anymore, unless someone can give me advice on what to do, or what this all means.

Perhaps you need to switch to another data source? Remember, you're still (sorta) misgendering someone.

**Comment by jbelien** [comment]
@rory I believe the last update fix this issue and do not "misgender" anyone anymore :)

**Comment by rory** [comment]
Cool. Using “cis” is a good choice, but I'd recommend using “trans” instead of “transgender” for consistancy.

**Comment by rory** [comment]
I think [the code to detect gender](https://github.com/openknowledgebe/equalstreetnames/blob/0fc8c56c33d0cea58fb545f5926110b127ac2503/scripts/geojson.php#L333-L347) has some issues. You are currently interpreting all “male” values ([`Q6581097`](https://www.wikidata.org/wiki/Q6581097)) as cis male, but cis male in wikidata is a different value: (`Q15145778`)](https://www.wikidata.org/wiki/Q15145778), which is a “subset of” male. (Trans male is also a subset of male in wikidata). Your code is unable to detect cis males! (same arguments for female obv.).

As [I pointed out](https://github.com/openknowledgebe/equalstreetnames/issues/13#issuecomment-600131742), this seems to be a problem with wikidata's data model which others trans people, and centers cis people.

I suggest you use a different dataset, or patch the data you pull from Wikidata.

**Comment by rory** [comment]
You are using the trans icon for the one (trans) male person, instead of the male icon. I suggest using the male icon for men.

You could add a “Female (trans): 0” as consistency in the display

**Comment by jbelien** [comment]
> I'd recommend using “trans” instead of “transgender” for consistancy.

Done! :)

> I think the code to detect gender has some issues. You are currently interpreting all “male” values (Q6581097) as cis male, but cis male in wikidata is a different value: (Q15145778)](https://www.wikidata.org/wiki/Q15145778), which is a “subset of” male. (Trans male is also a subset of male in wikidata). Your code is unable to detect cis males! (same arguments for female obv.).
>
> As I pointed out, this seems to be a problem with wikidata's data model which others trans people, and centers cis people.
>
> I suggest you use a different dataset, or patch the data you pull from Wikidata.

Thanks, I added (just in case) cis male and cis female wikidata item to my code.
As you said, all cis male/female are indeed categorized as male (`Q6581097`) or female (`Q6581072`). I know this is not "accurate" but that's how Wikidata decided to work and since we are using Wikidata, we have to go along.

If you know another source that we could use, let us know!

> You are using the trans icon for the one (trans) male person, instead of the male icon. I suggest using the male icon for men.

Not sure everyone knows what "cis" means (I didn't), I think separate icons will help understand more easily.

> You could add a “Female (trans): 0” as consistency in the display

Done! :)

**Comment by rory** [comment]
> but that's how Wikidata decided to work and since we are using Wikidata, we have to go along.

You don't *have* to use Wikidata. 😉 “Our datasource is biased, so we're replicating that bias” isn't a great argument to use.

> If you know another source that we could use, let us know!

You could just use OpenStreetMap? `name:etymology:gender=male/female/...`, `name:etymology:trans_or_cis=cis` _(I am unhappy with that subkey, maybe there's a better name)_ Or fork wikidata?

> Not sure everyone knows what "cis" means (I didn't),

I know. 🙂 And that's understandable. If you're going to do something with gender in 2020, you're going to hit this topic. To repeat my open offer, I'm always willing to have good faith confidential conversations with people if they don't understand.

> I think separate icons will help understand more easily.

That can be beneficial, but having a male gender symbol reaffirms this person's gender, and shows you recognize their gender. That's also useful.
