### ISSUE TITLE
Map is empty when running locally

### ISSUE THREAD

**Issue by realityfabric** [openknowledgebe/equalstreetnames#16]
After following the instructions to run the map locally (using https to download the repo instead of the git protocol, due to an authentication error) the map is empty and no statistics are shown.

![screenshot of EqualStreetNames web page where the map is completely gray and no stats are displayed](https://user-images.githubusercontent.com/8910652/77854800-3b7de080-71a1-11ea-97cf-42db81d51a95.png)

Is there more setup that I need to do to get it to display the map?

**Comment by jbelien** [comment]
Oh yes indeed, it is probably the Mapbox token that is missing !
I'll update the documentation tonight !
Thanks !

**Comment by jbelien** [comment]
I added the missing step ; see https://github.com/openknowledgebe/equalstreetnames#run-locally

**Comment by realityfabric** [comment]
Thanks! I'm not familiar with .env files and you have .env in your .gitignore, where should this .env file be placed? This is a really cool project btw

**Comment by jbelien** [comment]
> where should this .env file be placed?

Your `.env` should be in the root folder (next to `package.json` for instance).
It should look like this:

```env
MAPBOX_TOKEN="pk.ey1234567890ABCDEF"
```

> This is a really cool project btw

Thanks! ☺️

**Comment by realityfabric** [comment]
I put a file named `.env` in the root directory of the project, added `MAPBOX_TOKEN=[token]` but that didn't work until I added `require(dotenv).config()` in resources/map.ts (which threw some errors, but now the map works on the client side lol, definitely not the best solution)

After my tinkering it seems like the `.env` file isn't getting parsed at all (before adding the config code).

**Comment by jbelien** [comment]
I don't know what your environment is but `require('dotenv').config();` is not required.
ParcelJS do already use `dotenv` internally : https://parceljs.org/env.html

It works fine here on Ubuntu or Debian.

I suggest you remove ParcelJS cache by deleting the `.cache` folder and try to run it again !

**Comment by realityfabric** [comment]
Sorry that it took so long to respond!

I'm running Manjaro. I decided to start from scratch and put the `.env` file in before running it for the first time and it worked! It probably was the `.cache` folder like you said.

Thanks!
