### ISSUE TITLE
Show progress while ways.geojson is loaded

### ISSUE THREAD

**Issue by stalker314314** [openknowledgebe/equalstreetnames#25]
We are 50% done with Belgrade and produced ways.geojson is 11MB, and quite noticeable delay is viislbe before this is loaded. Since .geojson is pretty much as compact as-is, one option is to trim null values, but I doubt it will lead to any noticable changes in size. I think what is proper solution is to show some progress (determinate progress bar, or even indeterminate) while ways.geojson is being loaded in browser. Not sure if this is possible, but that is an idea

**Comment by stalker314314** [comment]
I would gladly send you PR, but my fork is far different than what I anticipated when I started working on it, so here is regular unified diff: https://upload.disroot.org/r/sSttfx6Z#526RHQ+S5AR5DlakM/9oy7giYuenwliGI/ySV30nt6c= 

I just used spin.js to show something to user. There are probably better ways (can we keep zip on server and download/unpack in browser). This thing reacts only when ways are finished downloading/rendering, not on relations! It is porbably ugly, but this is my first dive into JS, so feel free to ignore it:)

**Comment by jbelien** [comment]
Nice ! I'll have a look :)

**Comment by jbelien** [comment]
> There are probably better ways (can we keep zip on server and download/unpack in browser).

I would indeed recommend to use gzip encoding on your file(s) !
I don't know what web-server you're using but you can easily setup gzip encoding server side.
Look at <https://equalstreetnames.brussels/>:

- `relations.geojson` is 4.02 Mo but only 699.97 Ko are sent to the client ;
- `ways.geojson` is 3.28 Mo but only 721.78 KO are sent to the client ;

If you're using Apache : https://httpd.apache.org/docs/current/en/mod/mod_deflate.html
If you're using NGINX : https://docs.nginx.com/nginx/admin-guide/web-server/compression/
We're using Netlify and it's enabled by default.

**Comment by stalker314314** [comment]
I added this patch on Belgrade version - check it. We will continue to use it (it is not great, but I have no other option). I would argue that it is easy to misconfigure server (or overlook this setting) when deploying this code and it just pushes the can futher down the road. Belgrade will grow even more (probably ~20-30MB, so ~3-5MB gzipped). Funny thing how I noticed this - I was self-isolating myself in some remote locations over weekend and I noticed what it means not having broadband connection - it is borderline unusable:) I am OK if you don't want to merge this, I understand it is not best code there is out there, but I will keep it, as I think having this spinner is one small step towards people don't give up waiting on empty map

**Comment by jbelien** [comment]
Oh yes, I was just talking about the gzip encoding !

It's an excellent idea to add a loader :)
I'll do that when I have a bit of time !

**Comment by jbelien** [comment]
Took me a while to figure out what would be the best way to know the map is fully loaded (was working fine locally but not on production site) but I got it working use [`map.event:idle`](https://docs.mapbox.com/mapbox-gl-js/api/#map.event:idle).
