### ISSUE TITLE
null for label when label is not defined

### ISSUE THREAD

**Issue by stalker314314** [openknowledgebe/equalstreetnames#32]
I am using English language version. My config is set to `'languages' => ['sr', 'en'],` However, I am still getting nulls for labels, when there is no English version for label present. Here is picture and wikidata entry:

![slika](https://user-images.githubusercontent.com/188751/82153810-52fc5000-9859-11ea-8610-dd927a45a8c0.png)

https://www.wikidata.org/wiki/Q12751881

There are lot of cases when there is Serbian language label, but no English. Is this expected behavior, or I am doing something wrong? I tried browsing https://equalstreetnames.brussels/, but I couldn't find any "nulls". I think there should be some kind of fallback between languages when one does not exist (coalescing), but looking at `extractWikidata`, I don't see anything like that. I can live with this, but just want to confirm is it problem on my side:)

**Comment by jbelien** [comment]
It should have picked the Serbian name indeed (and then the English name if there is no Serbian name) !
I'll have a look !

**Comment by stalker314314** [comment]
> It should have picked the Serbian name indeed (and then the English name only if there is no Serbian name) !

But I am setting language to 'en' (`<html lang="en">`), so expectation is to use English, and, only if label is not available in English, to use 'sr'. Just saying to manage expectations

**Comment by jbelien** [comment]
Oh okay, I understand the cause now ! Thanks for the feedback !
This is caused by [`labels.ts`](https://github.com/openknowledgebe/equalstreetnames/blob/master/resources/wikidata/labels.ts), I'll fix it right now !
