### ISSUE TITLE
Found wrong gender defined

### ISSUE THREAD

**Issue by britiger** [openknowledgebe/equalstreetnames#61]
Maybe I found a wrong definition. 

In this line female (trans) (Q1052281) is counted as male:
https://github.com/openknowledgebe/equalstreetnames/blob/3330c2267465cc651356184849b11a29747c81be/scripts/library/geojson/wikidata.php#L134

The definition for define FX here will never been reached:
https://github.com/openknowledgebe/equalstreetnames/blob/3330c2267465cc651356184849b11a29747c81be/scripts/library/geojson/wikidata.php#L143

There are an entity for cis male : Q15145778

**Comment by jbelien** [comment]
WOW! Nice catch, no idea how I got this wrong.
I'll fix this ASAP !

**Comment by jbelien** [comment]
🚨 Ping @stalker314314 @robinlinde @gislars
