### ISSUE TITLE
change wording in summary

### ISSUE THREAD

**Issue by seppesantens** [openknowledgebe/equalstreetnames#97]
In stead of "Out of 2986 streetnames, 632 (21.17%) are based on a person.", it might be better to say "Out of ... streetnames, ... have been found to be named after a person." (or something similar). This is a solution for cities that are online but where there are still (a lot of) etymology tags missing.

**Comment by jbelien** [comment]
How would you translate that in Dutch ?

In French, I used the following
> Sur les ... noms de rue, ... ont été trouvés être attribué à une personne.

**Comment by seppesantens** [comment]
"Van de ... straatnamen zijn er ... gevonden die naar een persoon verwijzen."
